### ISSUE TITLE
Add js test and docs back to CI

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/widget-ts-cookiecutter#92]
For now this PR skips tests and docs, just so we can have a basic workflow working for other PRs. But we should eventually add them back, and also check the generated workflow from the cookiecutter is also correct.

_Originally posted by @jtpio in https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/91#issuecomment-788748143_

**Comment by jtpio** [comment]
Thanks @ianhi.

For the tests, which might be fixed by #86: 

https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/78716a69743e65865e89d097c2a28437b9d62820/.github/workflows/build.yml#L61-L63

For the docs:

https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/78716a69743e65865e89d097c2a28437b9d62820/.github/workflows/build.yml#L65-L70

And for the generated cookiecutter workflow:

https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/78716a69743e65865e89d097c2a28437b9d62820/%7B%7Bcookiecutter.github_project_name%7D%7D/.github/workflows/build.yml#L49-L61
